# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: The event
    url: /#about
    parent: About
    weight: 10
  - name: The organisers
    url: organisers
    parent: About
    weight: 20
  - name: What to expect
    url: /#features
    weight: 30
  - name: Programme
    url: /#programme
    weight: 40
  - name: Community
    url: /#who
    weight: 50
